Fixes #428: Implement `FakeFS::File#string` for Ruby 2.6.x CSV reading
- We want to be able to invoke `CSV.read` with `FakeFS::File` objects
- Recent changes to the CSV standard library now require this method

---

Fixes error:

```
undefined method `string' for #<FakeFS::File:0x00007fdb072b73e0>
```

---

Changes to how CSV's are read were introduced in Ruby 2.6.x.
When parsing the CSV, `CSV::Parser` will break any non `File`
object into chunks of 1024 bytes. If there's more than one chunk
(i.e. file > 1024 bytes), each chunk will have `#string` invoked.

In this spec, we generate a `FakeFS::File` with 1025 bytes of data,
which pushes us just over the threshold of 1024 bytes. This provides
an adequate test setup.

We could make this number much higher than 1025. The only thing
that matters is that the file is larger than 1024 bytes.